spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/swagger_test
    username: swagger
    password: swagger#1
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, validate, update, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: SwaggerTest
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: /static/
server:
  port: 3000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){green} %clr(%-5level) %clr(${PID:-}){magenta} %clr(---){faint} [PayrollCalc] %clr(%logger - %M{10}){cyan} - %msg%n)"
  level:
    root: INFO
    org.study: DEBUG