spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/swagger_test
    username: swagger
    password: swagger#1
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, validate, update ? ??? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: SwaggerTest
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui