spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/swagger_test
    username: postgres
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  batch:
    jdbc:
      initialize-schema: always # Application 실행 시 메타 데이터 테이블 생성
    job:
      enabled: false # Application 실행 시 시작 방지
  jpa:
    hibernate:
      # ??? ????? ?? DB ???? ??
      ddl-auto: update # create, create-drop, validate, update, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: SwaggerTest
server:
  port: 3000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
    session:
      timeout: 1800
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui